export const items = {
  pembina: [
    {
      id: 1,
      title: "Dr.Eng Danu Dwi Sanjoyo, ST., MT.",
      image: "/pembina/DWJ.png",
      codedosen: "DWJ",
      nip: "14880082",
      posisi: "Pembina Utama",
    },
    {
      id: 2,
      title: "Sri Astuti, S.T., M.T.",
      image: "/pembina/TUI.png",
      codedosen: "TUI",
      nip: "20850004",
      posisi: "Pembina",
    },
    {
      id: 3,
      title: "Sussi, S.Si., MT.",
      image: "/pembina/SUI.png",
      codedosen: "SUI",
      nip: "20830010",
      posisi: "Pembina",
    },
    {
      id: 4,
      title: "Bagus Aditya, S.T., M.T",
      image: "/pembina/BGY.png",
      codedosen: "BGY",
      nip: "20900007",
      posisi: "Pembina",
    },
    {
      id: 4,
      title: "Dr.Eng. Favian Dewanta, S.T., M.Eng.",
      image: "/pembina/FAV.png",
      codedosen: "FAV",
      nip: "15870022",
      posisi: "Pembina",
    },

  ],
  asisten: [
    {
      id: 1,
      title: "Ahda Akmalul Ilmi",
      desc: "Node.js, Next.js, Python, Docker, Nginx",
      image: "/asisten/AAI.jpg",
      codeass: "AAI",
      nim: "1101202381",
      divisi: "Cybersecurity",
    },
    {
      id: 2,
      title: "Hubert Igor",
      desc: "network security, ethical hacking, data privacy",
      image: "/asisten/HUB.jpg",
      codeass: "HUB",
      nim: "1303200063",
      divisi: "Cybersecurity",
    },
    {
      id: 3,
      title: "Muhammad Rafi Ediananta",
      desc: "Git, Cloud Computing, Security Testing",
      image: "/asisten/REN.jpg",
      codeass: "REN",
      nim: "1101210178",
      divisi: "Cybersecurity",
    },
    {
      id: 4,
      title: "M. Reza Manazil Al Qomar",
      desc: "C, Python, Java, Dokcer",
      image: "/asisten/EZA.jpg",
      codeass: "EZA",
      nim: "1101204023",
      divisi: "Cybersecurity",
    },
    {
      id: 5,
      title: "Rayhan Dhafi",
      desc: "Project Management, Linux, Cloud Computing",
      image: "/asisten/RDA.jpg",
      codeass: "RDA",
      nim: "1101201500",
      divisi: "Cybersecurity",
    },
    {
      id: 6,
      title: "Satria Winekas Herlambang",
      desc: "Linux dan SIS admin, DevOps",
      image: "/asisten/POW.jpg",
      codeass: "POW",
      nim: "1101204298",
      divisi: "Cybersecurity",
    },
    {
      id: 7,
      title: "Adam Hadi Pratama",
      desc: "Apache Superset, Odoo, Python",
      image: "/asisten/ADM.jpg",
      codeass: "ADM",
      nim: "1101202001",
      divisi: "Big Data",
    },
    {
      id: 8,
      title: "Devan Ramadhana",
      desc: "Data Visualization, Big Data, Python",
      image: "/asisten/JMD.jpg",
      codeass: "JMD",
      nim: "1101210396",
      divisi: "Big Data",
    },
    {
      id: 9,
      title: "Dias Daffa Wiwaha",
      desc: "Machine Learning, Python, Data Analysis",
      image: "/asisten/DDW.jpg",
      codeass: "DDW",
      nim: "1101201482",
      divisi: "Big Data",
    },
    {
      id: 10,
      title: "Rafi Andhika Putra",
      desc: "Machine Learning, Pyhton, Data Anaylsis",
      image: "/asisten/FII.jpg",
      codeass: "FII",
      nim: "1101213149",
      divisi: "Big Data",
    },
    {
      id: 11,
      title: "Retno Fauziah Istiqomah",
      desc: "Machine Learning, Python",
      image: "/asisten/ENQ.jpg",
      codeass: "ENQ",
      nim: "1303204088",
      divisi: "Big Data",
    },
    {
      id: 12,
      title: "Zaidan Muhammad Mahdi",
      desc: "Data Science, Machine Learning, Python",
      image: "/asisten/DAN.jpg",
      codeass: "DAN",
      nim: "1101202181",
      divisi: "Big Data",
    },
    // {
    //   id: 13,
    //   title: "Zaidan Muhammad Mahdi",
    //   desc: "Data Science, Machine Learning, Python",
    //   image:
    //     "/asisten/DAN.jpg",
    //   codeass: "DAN",
    //   nim: "1101202181",
    //   divisi: "Big Data",
    // },
    {
      id: 14,
      title: "Fabiano Abbey Karo Sekali",
      desc: "Game Mechanism, C#, Unity",
      image: "/asisten/BEY.jpg",
      codeass: "BEY",
      nim: "1101202469",
      divisi: "GameTech",
    },
    {
      id: 15,
      title: "Fellica Clara Cindy",
      desc: "Design, Adobe Illustrator",
      image: "/asisten/FEL.jpg",
      codeass: "FEL",
      nim: "1101210162",
      divisi: "GameTech",
    },
    {
      id: 16,
      title: "Geva Almer Hariri",
      desc: "Design, Adobe Illustrator",
      image: "/asisten/GEV.jpg",
      codeass: "GEV",
      nim: "1101213144",
      divisi: "GameTech",
    },
    {
      id: 17,
      title: "Moch Firza Yudistira Meizia",
      desc: "Music Design, Adobe Illustrator, FL Studio",
      image: "/asisten/FYI.jpg",
      codeass: "FYI",
      nim: "1101210233",
      divisi: "GameTech",
    },
    {
      id: 18,
      title: "Raehan Abdillah",
      desc: "Game Mechanism, C#, Unity",
      image: "/asisten/FIN.jpg",
      codeass: "FIN",
      nim: "1101213177",
      divisi: "GameTech",
    },
    {
      id: 19,
      title: "Abdurrasyid Malvin Nugraha",
      desc: "Unity, UI/UX Designer, Figma",
      image: "/asisten/MVN.jpg",
      codeass: "MVN",
      nim: "1101213177",
      divisi: "GIS",
    },
    {
      id: 20,
      title: "Divany Maulidyna Putri",
      desc: "Blender",
      image: "/asisten/DIV.jpg",
      codeass: "DIV",
      nim: "1101213180",
      divisi: "GIS",
    },
    {
      id: 21,
      title: "Fadilah Putri Sukoco",
      desc: "UI/UX Designer, Cloud Computing",
      image: "/asisten/DIL.jpg",
      codeass: "DIL",
      nim: "1101204044",
      divisi: "GIS",
    },
    {
      id: 22,
      title: "M. Priambodo Satrio Wibowo",
      desc: "Blender, unity",
      image: "/asisten/TYO.jpg",
      codeass: "TYO",
      nim: "1101154322",
      divisi: "GIS",
    },
    {
      id: 23,
      title: "Yulintyandra Puja Antanita",
      desc: "Blender",
      image: "/asisten/LIN.jpg",
      codeass: "LIN",
      nim: "1101213241",
      divisi: "GIS",
    },
  ],

  caas: [
    {
      id: 1,
      title: "Thufail Agung Fatih",
      desc: "TT-45-03",
      image: "/team/thufail.png",
      nim: "1101210333",
      divisi: "Cybersecurity",
    },
    {
      id: 2,
      title: "Muhammad Surya Danendra Pabana        ",
      desc: "TT-45-02",
      image: "/team/surya.png",
      nim: "1101210209",
      divisi: "Cybersecurity",
    },
    {
      id: 3,
      title: "Muhammad Reza Aditria        ",
      desc: "TT-45-04",
      image: "/team/reza.png",
      nim: "1101210282",
      divisi: "Cybersecurity",
    },
    {
      id: 4,
      title: "Pandu Dwi Nugraha Surya Putra",
      desc: "TT-46-07",
      image: "/team/pandu.png",
      nim: "1101220156",
      divisi: "Cybersecurity",
    },
    {
      id: 5,
      title: "Agni Pulung Tondo Drawino",
      desc: "TT-45-08",
      image: "/team/Agni.png",
      nim: "1101210072",
      divisi: "Big Data",
    },
    {
      id: 6,
      title: "Alfarelzi",
      desc: "TT-45-05",
      image: "/team/farel.png",
      nim: "1101210384",
      divisi: "Big Data",
    },
    {
      id: 7,
      title: "Rr Meidita Thifal Lelyta",
      desc: "TT-45-07",
      image: "/team/mei.png",
      nim: "1101213060",
      divisi: "Big Data",
    },
    {
      id: 8,
      title: "Nathanael Dwi Cahyo",
      desc: "TT-45-10",
      image: "/team/nathan.png",
      nim: "1101210329",
      divisi: "GameTech",
    },
    {
      id: 9,
      title: "Putra Pratama Sijabat",
      desc: "TT-45-09",
      image: "/team/Putra.png",
      nim: "1101210298",
      divisi: "GameTech",
    },
    {
      id: 10,
      title: "Rizki Ananda",
      desc: "TT-46-07",
      image: "/team/rizki.png",
      nim: "1101223162",
      divisi: "GameTech",
    },
    {
      id: 11,
      title: "Mohammad Farrel William",
      desc: "TT-45-03",
      image: "/team/farelw.png",
      nim: "1101210306",
      divisi: "GameTech",
    },
    {
      id: 12,
      title: "Fayyadh Asady",
      desc: "TT-46-09",
      image: "/team/Fayyadh.png",
      nim: "1101220353",
      divisi: "GameTech",
    },
    {
      id: 13,
      title: "Firscha Aulia Ghassani Fikri",
      desc: "TT-45-01",
      image: "/team/firscha.png",
      nim: "1101210390",
      divisi: "GIS",
    },
    {
      id: 14,
      title: "Muhammad Abdul Hakim",
      desc: "TT-45-08",
      image: "/team/hakim.jpg",
      nim: "1101213039",
      divisi: "GIS",
    },
    {
      id: 15,
      title: "Muhammad Abyan Harits",
      desc: "TT-45-07",
      image: "/team/abyan.png",
      nim: "1101210258",
      divisi: "GIS",
    },
  ],
};
